### ISSUE TITLE
Upgrade to Angular 12

### ISSUE THREAD

**Issue by timvandenhof** [staticwebdev/angular-basic#20]
Meanwhile Angular 12 has been released.
Let's help new projects start with an up-to-date Angular version.
https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49

Upgrade steps:
- [ ] Run ng update @angular/core@12 @angular/cli@12 which should bring you to version 12 of Angular.
- [ ] Angular now requires TypeScript 4.2. ng update will update you automatically.
- [ ] IE11 support has been deprecated. Find details in the RFC for IE11 removal.
- [ ] You can no longer use Angular with Node.js version 10 or older

Source: https://update.angular.io/?v=11.0-12.0

**Comment by manekinekko** [comment]
Hey, thank you for opening this issue. We updated this template to Angular 13 (https://github.com/staticwebdev/angular-basic/commit/136fc2af607350fbd706cb0fa0b27cbb770b6bf6)
